import React, { useEffect, useState } from 'react';
import { apiService } from '../../services/api';
import { User, Permission } from '../../types';
import { Dialog } from '../app/Dialog';
import { ErrorNotice, Loading } from '../app/Primitives';
interface Props { user:User|null;isOpen:boolean;onClose:()=>void;onSuccess:()=>void; }
export const ManageAccessDrawer:React.FC<Props>=({user,isOpen,onClose,onSuccess})=>{
  const [permissions,setPermissions]=useState<Permission[]>([]);const [overrides,setOverrides]=useState<Record<number,'ALLOW'|'DENY'|'INHERIT'>>({});const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!user||!isOpen)return;let alive=true;setLoading(true);setError('');apiService.getUserPermissions(user.user_id).then(result=>{if(!alive)return;setLoading(false);if(result.status==='success'&&result.data){setPermissions(result.data.permissions);setOverrides(Object.fromEntries(result.data.permissions.map(permission=>[permission.id,permission.is_override?permission.effect||'INHERIT':'INHERIT'])));}else setError(result.message||'Izin belum dapat dimuat.');});return()=>{alive=false;};},[user,isOpen]);
  const save=async()=>{if(!user)return;setBusy(true);const result=await apiService.updateUserPermissions(user.user_id,Object.entries(overrides).map(([permission_id,effect])=>({permission_id:Number(permission_id),effect})));setBusy(false);if(result.status==='success')onSuccess();else setError(result.message||'Izin belum tersimpan.');};
  return <Dialog open={isOpen} title={'Hak akses · '+(user?.name||'Pengguna')} onClose={()=>{if(!busy)onClose();}}><p className="field-hint mb-5">Ikuti peran menggunakan aturan bawaan. Izin khusus hanya berlaku pada pengguna ini dan tetap mengikuti cakupan data serta batas operasi administrator.</p><ErrorNotice message={error}/>{loading?<Loading/>:<div className="form-stack">{permissions.map(permission=><label key={permission.id} className="flex items-start justify-between gap-4 border-b border-slate-100 pb-3"><span><span className="field-label block">{permission.name}</span><span className="muted">{permission.code} · {permission.effect==='ALLOW'?'Diizinkan':'Ditolak'}</span></span><select className="input !w-auto text-xs" aria-label={'Izin '+permission.name} value={overrides[permission.id]||'INHERIT'} onChange={event=>setOverrides(previous=>({...previous,[permission.id]:event.target.value as 'ALLOW'|'DENY'|'INHERIT'}))}><option value="INHERIT">Ikuti peran</option><option value="ALLOW">Izinkan</option><option value="DENY">Tolak</option></select></label>)}</div>}<button className="btn btn-primary w-full mt-6" disabled={loading||busy||Boolean(error)} onClick={save}>{busy?'Menyimpan…':'Simpan hak akses'}</button></Dialog>;
};
