import React, { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Building2, Check, CheckCheck, Clock3, Copy, Hash, LockKeyhole, MessageSquare, RefreshCw, Send, UserRound } from 'lucide-react';
import { AppShell } from '../../components/app/AppShell';
import { ErrorNotice, Field, formatDate, LiveTimeAgo, Loading, nextStatuses, Priority, Status, statusLabels } from '../../components/app/Primitives';
import { SlaCountdown } from '../../components/features/SlaCountdown';
import { EvidenceAttachments } from '../../components/app/EvidenceAttachments';
import { apiService } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { Ticket, ThreadMessage, TicketPriority, TicketStatus, User, TicketReopenRequest } from '../../types';
import { parseTicketDetails, extractAttachmentsAndCleanText } from '../../utils/ticketFormatter';
import { CASCADING_DEPARTMENTS } from '../../config/services';

export function TicketDetail() {
  const {id=''}=useParams(); const {isStaff,hasPermission}=useAuth(); const {success}=useToast();
  const [ticket,setTicket]=useState<Ticket|null>(null);const [threads,setThreads]=useState<ThreadMessage[]>([]);const [requests,setRequests]=useState<TicketReopenRequest[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
  const [message,setMessage]=useState('');const [internal,setInternal]=useState(false);const [nextStatus,setNextStatus]=useState('');const [note,setNote]=useState('');
  const [reason,setReason]=useState('');const [reviewNote,setReviewNote]=useState('');const [operators,setOperators]=useState<User[]>([]);const [operator,setOperator]=useState('');const [priority,setPriority]=useState('');  const [unit,setUnit]=useState('');
  const [copied,setCopied]=useState(false);
  const copyTicketId=()=>{
    if(!ticket?.ticket_id)return;
    navigator.clipboard.writeText(ticket.ticket_id);
    setCopied(true);
    success('Nomor ID tiket lengkap disalin ke clipboard.');
    setTimeout(()=>setCopied(false),2000);
  };
  const messageKey=useRef(crypto.randomUUID());
  useEffect(()=>{
    let live=true;let running=false;setLoading(true);
    const load=async()=>{if(running || document.hidden)return;running=true;const [result,history]=await Promise.all([apiService.getTicketDetail(id),apiService.getTicketReopenRequests(id)]);if(live){if(result.status==='success'&&result.data){setTicket(result.data.ticket);setThreads(result.data.threads);setError('');}else setError(result.message||'Tiket belum dapat dimuat.');if(history.status==='success')setRequests(history.data||[]);setLoading(false);}running=false;};
    void load();const timer=setInterval(load,15000);return()=>{live=false;clearInterval(timer);};
  },[id,revision]);
  useEffect(()=>{if(isStaff)void apiService.getOperators().then(result=>{if(result.status==='success')setOperators(result.data||[]);});},[isStaff]);
  const refresh=()=>setRevision(value=>value+1);
  const send=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');const result=await apiService.addThreadMessage({ticket_id:id,message,visibility:internal?'internal':'public',idempotency_key:messageKey.current});setBusy(false);if(result.status==='success'){setMessage('');messageKey.current=crypto.randomUUID();success(internal?'Catatan internal disimpan.':'Pesan terkirim.');refresh();}else setError(result.message||'Pesan belum terkirim. Isi pesan tetap tersedia.');};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!ticket)return;setBusy(true);setError('');const result=await apiService.updateTicketStatus({ticket_id:id,version:ticket.version,...(nextStatus?{status:nextStatus as TicketStatus}:{}),...(priority?{priority:priority as TicketPriority}:{}),...(operator?{assigned_operator:operator==='unassigned'?'':operator}:{}),...(unit?{assigned_upt:unit}:{}),...(note?{note}:{})});setBusy(false);if(result.status==='success'){success('Perubahan tiket disimpan.');setNextStatus('');setNote('');setPriority('');setOperator('');setUnit('');refresh();}else{setError(result.message||'Perubahan belum tersimpan.');if(result.code===409){const latest=await apiService.getTicketDetail(id);if(latest.data)setTicket(latest.data.ticket);}}};
  const reopen=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);const result=await apiService.requestTicketReopen(id,reason);setBusy(false);if(result.status==='success'){setReason('');success('Permohonan buka kembali dikirim.');refresh();}else setError(result.message||'Permohonan belum terkirim.');};
  const review=async(action:'APPROVE'|'REJECT')=>{if(reviewNote.trim().length<10){setError('Catatan keputusan minimal 10 karakter.');return;}setBusy(true);const result=await apiService.reviewTicketReopen(id,action,reviewNote);setBusy(false);if(result.status==='success'){setReviewNote('');success('Keputusan disimpan.');refresh();}else setError(result.message||'Keputusan belum tersimpan.');};
  if(loading&&!ticket)return <AppShell><Loading label="Memuat detail tiket…"/></AppShell>;
  if(!ticket)return <AppShell><ErrorNotice message={error} retry={refresh}/><Link className="btn btn-secondary" to={isStaff?'/dashboard':'/my-tickets'}>Kembali ke daftar</Link></AppShell>;
  const parsed=parseTicketDetails(ticket.description||'',ticket.category,ticket.attachments);
  const options=nextStatuses[ticket.status].filter(status=>hasPermission(status==='resolved'?'ticket.resolve':status==='closed'?'ticket.close':'ticket.change_status'));
  const pending=requests.find(request=>request.status==='PENDING');
  const currentOperator=operators.find(item=>item.user_id===ticket.assigned_operator);
  const allowReply=ticket.status!=='closed'&&(hasPermission('ticket.reply')||hasPermission('ticket.reply_own'));
  return <AppShell><Link className="btn btn-link mb-4" to={isStaff?'/dashboard':'/my-tickets'}><ArrowLeft size={15}/>Kembali ke daftar tiket</Link><div className="page-heading"><div><div className="flex flex-wrap items-center gap-2 mb-2.5"><div className="inline-flex items-center gap-1.5 font-mono text-xs sm:text-[13px] font-bold text-[#0D5C75] bg-[#F0F7FA] px-2.5 py-1 rounded-md border border-[#CDE3EC]" title="Nomor ID Tiket Lengkap"><Hash size={13} className="text-[#0D5C75]/60 shrink-0"/> <span className="select-all tracking-tight break-all">{ticket.ticket_id}</span></div><button type="button" onClick={copyTicketId} className="inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-semibold text-teal-700 hover:text-teal-800 bg-teal-50 hover:bg-teal-100 rounded-md border border-teal-200 transition-colors cursor-pointer shadow-2xs active:scale-95 shrink-0" title="Salin ID Tiket Lengkap" aria-label="Salin nomor ID tiket lengkap">{copied?<Check size={13} className="text-emerald-600"/>:<Copy size={13}/>}<span>{copied?'Tersalin!':'Salin ID'}</span></button></div><h1 className="page-title break-words">{ticket.subject}</h1><div className="flex flex-wrap gap-3 items-center mt-4"><Status value={ticket.status}/><Priority value={ticket.priority}/><SlaCountdown slaTarget={ticket.sla_due_at} isClosed={['closed','resolved'].includes(ticket.status)} compact /><span className="muted flex items-center gap-1.5"><span>Dibuat {formatDate(ticket.created_at)}</span><span>•</span><span className="text-teal-700 font-semibold"><LiveTimeAgo date={ticket.created_at}/></span></span></div></div><button className="btn btn-secondary" onClick={refresh} disabled={loading}><RefreshCw size={15} className={loading?'animate-spin':''}/>Muat ulang</button></div><ErrorNotice message={error}/>
    <div className="detail-layout"><div className="detail-content"><section className="panel panel-pad"><h2 className="panel-title">Rincian laporan</h2><p className="message-body mt-4">{parsed.cleanDescription}</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 border-t border-slate-100 pt-5 mt-5"><div><p className="muted flex gap-2 items-center"><Hash size={14}/>Nomor ID tiket</p><p className="text-xs font-mono font-bold text-slate-700 mt-2 select-all break-all">{ticket.ticket_id}</p></div><div><p className="muted flex gap-2 items-center"><Building2 size={14}/>Kantor & lokasi</p><p className="text-xs text-slate-700 mt-2 leading-relaxed">{ticket.office_name||'Tidak tercatat'}<br/>{ticket.location||parsed.location||'—'}</p></div><div><p className="muted flex gap-2 items-center"><UserRound size={14}/>Pelapor</p><p className="text-xs text-slate-700 mt-2 leading-relaxed">{ticket.requester_name}<br/>{ticket.requester_email}</p></div></div>{parsed.attachments.length>0&&<div className="mt-6"><h3 className="field-label mb-3">Bukti & lampiran</h3><EvidenceAttachments files={parsed.attachments}/></div>}</section>
    <section className="panel panel-pad"><div className="flex items-center gap-2"><MessageSquare size={18} className="text-teal-700"/><h2 className="panel-title mb-0">Percakapan & tindak lanjut</h2></div><p className="field-hint mt-2">{isStaff?'Balasan publik dapat dibaca pelapor. Catatan internal hanya terlihat oleh petugas yang berwenang.':'Tambahkan informasi yang diperlukan dan ikuti respons dari petugas.'}</p><div aria-live="polite" aria-relevant="additions">{threads.map(thread=>{const parsedMessage=extractAttachmentsAndCleanText(thread.message);return <article key={thread.thread_id} className={'message-item '+(thread.visibility==='internal'?'message-internal':'')}><div className="message-meta"><strong>{thread.sender_name||'Petugas'}{thread.visibility==='internal'&&<span className="ml-2 text-amber-700">· Internal</span>}</strong><time className="muted flex items-center gap-1.5"><span>{formatDate(thread.created_at)}</span><span>•</span><span className="text-teal-700 font-medium"><LiveTimeAgo date={thread.created_at}/></span></time></div><p className="message-body">{parsedMessage.cleanText}</p><EvidenceAttachments files={parsedMessage.attachments}/></article>;})}</div>
    {allowReply?<form className="form-stack border-t border-slate-100 pt-5 mt-3" onSubmit={send}>{isStaff&&hasPermission('ticket.reply')&&<label className="flex items-center gap-2 text-xs text-slate-600"><input className="accent-teal-700" type="checkbox" checked={internal} onChange={event=>setInternal(event.target.checked)}/><LockKeyhole size={14}/>Jadikan catatan internal (tidak dikirim ke pelapor)</label>}<Field label={internal?'Catatan internal':'Balasan'}><textarea className={'input '+(internal?'bg-amber-50':'')} value={message} onChange={event=>setMessage(event.target.value)} maxLength={10000} required placeholder={internal?'Catat hasil investigasi atau koordinasi petugas…':'Tulis informasi atau tindak lanjut yang jelas…'} rows={4}/></Field><div className="flex justify-between gap-4 items-center"><span className="muted">{message.length}/10.000 karakter</span><button className="btn btn-primary" disabled={busy||!message.trim()}><Send size={15}/>{busy?'Mengirim…':internal?'Simpan catatan':'Kirim balasan'}</button></div></form>:<div className="info-notice mt-5 flex gap-2 items-start"><LockKeyhole size={17} className="mt-1 shrink-0"/>Percakapan sudah ditutup. Jika kendala kembali terjadi, ajukan buka kembali tiket dengan alasannya.</div>}</section>
    {ticket.status==='closed'&&<section className="panel panel-pad"><h2 className="panel-title">Kendala belum terselesaikan?</h2>{pending?<div className="info-notice mt-4"><strong>Permohonan sedang ditinjau</strong><p className="mt-2">{pending.reason}</p><p className="muted mt-2">Diajukan {formatDate(pending.created_at)} oleh {pending.requester_name}</p></div>:<form className="form-stack mt-4" onSubmit={reopen}><Field label="Alasan buka kembali" hint="Jelaskan kendala yang masih terjadi atau muncul kembali."><textarea className="input" value={reason} onChange={event=>setReason(event.target.value)} minLength={10} maxLength={2000} required/></Field><button className="btn btn-secondary self-start" disabled={busy}>Ajukan buka kembali</button></form>}{pending&&isStaff&&hasPermission('ticket.reopen')&&<div className="form-stack mt-5"><Field label="Catatan keputusan" required><textarea className="input" value={reviewNote} onChange={event=>setReviewNote(event.target.value)} minLength={10} maxLength={2000} placeholder="Alasan persetujuan atau penolakan…"/></Field><div className="flex flex-wrap gap-3"><button className="btn btn-primary" disabled={busy} onClick={()=>review('APPROVE')}>Setujui buka kembali</button><button className="btn btn-danger" disabled={busy} onClick={()=>review('REJECT')}>Tolak permohonan</button></div></div>}{requests.filter(request=>request.status!=='PENDING').map(request=><div key={request.request_id} className="mt-4 border-t pt-4"><p className="field-label">{request.status==='APPROVED'?'Disetujui':'Ditolak'} · {request.reviewer_name}</p><p className="muted mt-1">{request.review_note} · {formatDate(request.reviewed_at)}</p></div>)}</section>}</div>
    <aside className="detail-sidebar"><section className="panel panel-pad"><div className="flex items-center justify-between gap-2 mb-3"><div className="flex items-center gap-2"><Clock3 size={17} className="text-teal-700"/><h2 className="panel-title mb-0">Target penanganan</h2></div><span className="text-[10px] font-bold text-teal-800 bg-teal-50 border border-teal-200 px-2 py-0.5 rounded uppercase tracking-wider">SLA Real-time</span></div><div className="mb-3"><SlaCountdown slaTarget={ticket.sla_due_at} isClosed={['closed','resolved'].includes(ticket.status)} showSeconds /></div><p className="text-xs font-semibold text-slate-700 flex items-center justify-between border-t border-slate-100 pt-3 mt-2"><span className="text-slate-500 font-normal">Batas waktu target:</span><span>{formatDate(ticket.sla_due_at)}</span></p><p className="field-hint mt-2">{['closed','resolved'].includes(ticket.status)?'Penanganan sudah selesai. Target disimpan sebagai rekam jejak.':new Date(ticket.sla_due_at)<new Date()?'Target waktu sudah terlewati. Tiket perlu diprioritaskan.':'Target dihitung sejak laporan dibuat sesuai prioritas.'}</p><div className="border-t border-slate-100 mt-5 pt-4"><p className="muted">Unit penanganan</p><p className="field-label mt-2 leading-relaxed">{ticket.assigned_upt||'Belum ditetapkan'}</p><p className="muted mt-4">Petugas penanggung jawab</p><p className="field-label mt-2">{currentOperator?.name||ticket.assigned_operator||'Belum ditugaskan'}</p></div></section>
    {isStaff&&ticket.status!=='closed'&&<form className="panel panel-pad form-stack" onSubmit={save}><h2 className="panel-title mb-0">Tindak lanjut petugas</h2>{options.length>0&&<Field label="Ubah status"><select className="input" value={nextStatus} onChange={event=>setNextStatus(event.target.value)}><option value="">Pertahankan status</option>{options.map(status=><option key={status} value={status}>{statusLabels[status]}</option>)}</select></Field>}{hasPermission('ticket.assign')&&<><Field label="Penanggung jawab"><select className="input" value={operator} onChange={event=>setOperator(event.target.value)}><option value="">Pertahankan petugas</option><option value="unassigned">Belum ditugaskan</option>{operators.map(item=><option key={item.user_id} value={item.user_id}>{item.name}</option>)}</select></Field><Field label="Unit penanganan"><select className="input" value={unit} onChange={event=>setUnit(event.target.value)}><option value="">Pertahankan unit</option>{CASCADING_DEPARTMENTS.map(item=><option key={item.id} value={item.uptUnit}>{item.uptUnit}</option>)}</select></Field></>}{hasPermission('ticket.change_priority')&&ticket.status!=='resolved'&&<Field label="Prioritas"><select className="input" value={priority} onChange={event=>setPriority(event.target.value)}><option value="">Pertahankan prioritas</option><option value="Low">Rendah</option><option value="Medium">Sedang</option><option value="High">Tinggi</option><option value="Urgent">Mendesak</option></select></Field>}<Field label="Catatan tindak lanjut" hint={['waiting','resolved','closed'].includes(nextStatus)?'Wajib minimal 10 karakter; catatan ini dapat dibaca pelapor.':'Catat alasan perubahan agar mudah ditelusuri.'} required={['waiting','resolved','closed'].includes(nextStatus)}><textarea className="input" rows={4} value={note} onChange={event=>setNote(event.target.value)} maxLength={10000} minLength={['waiting','resolved','closed'].includes(nextStatus)?10:undefined} required={['waiting','resolved','closed'].includes(nextStatus)}/></Field><button className="btn btn-primary" disabled={busy||(!nextStatus&&!priority&&!operator&&!note&&!unit)}><CheckCheck size={16}/>{busy?'Menyimpan…':'Simpan tindak lanjut'}</button></form>}
    <section className="panel panel-pad workflow-panel"><h2 className="panel-title">Alur penanganan</h2><ol className="workflow-list">{(['open','in_progress','waiting','resolved','closed'] as TicketStatus[]).map((status,index)=><li className={ticket.status===status?'current':''} aria-current={ticket.status===status?'step':undefined} key={status}><span>{index+1}</span>{statusLabels[status]}</li>)}</ol><p className="field-hint mt-3">Tahap menunggu digunakan jika petugas membutuhkan informasi tambahan.</p></section></aside></div>
  </AppShell>;
}
